CREATE DATABASE `Empresa`;

USE `Empresa`;

CREATE TABLE
    `Funcionário` (
        `CODIGO_FUNC` INTEGER NOT NULL AUTO_INCREMENT,
        `NOME_FUNC` VARCHAR(200) NOT NULL,
        PRIMARY KEY (CODIGO_FUNC)
    );

CREATE TABLE
    `Projeto` (
        `CODIGO_PROJ` INTEGER NOT NULL AUTO_INCREMENT,
        `NOME_PROJ` VARCHAR(300) NOT NULL,
        PRIMARY KEY (CODIGO_PROJ)
    );